javascript_compressor: yui

javascripts:
  base:
    - public/javascripts/vendor/jquery-1.4.2.js
    - public/javascripts/vendor/jquery.rails.js
    - public/javascripts/vendor/jquery.timeago.js
    - public/javascripts/vendor/css_browser_selector.js
    - public/javascripts/vendor/shuriken/**/*.js
    - public/javascripts/eoraptor.js
    - public/javascripts/eoraptor/util.js
    - public/javascripts/eoraptor/twitter.js
    - public/javascripts/eoraptor/timestamps.js
  html5_shiv:
    - public/javascripts/vendor/html5.js
  disqus:
    - public/javascripts/eoraptor/disqus.js
  admin:
    - public/javascripts/vendor/jquery-1.4.2.js
    - public/javascripts/vendor/jquery.rails.js
    - public/javascripts/vendor/css_browser_selector.js
    - public/javascripts/eoraptor.js
    - public/javascripts/eoraptor/util.js
  github:
    - public/javascripts/vendor/date_iso8601.js
    - public/javascripts/eoraptor/git_hub.js
stylesheets:
  admin:
    - public/stylesheets/eoraptor-admin.css
  base:
    - public/stylesheets/eoraptor.css
