---
development:
  adapter: postgresql
  encoding: utf8
  database: eoraptor_development
  user: eoraptor
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: eoraptor_test
  user: eoraptor
  password: 
